#!/bin/bash
BASEDIR=`dirname "${0}"`
cd "$BASEDIR"
sudo echo
read -e -p "Enter GCC version number: " ver
archive=(gcc-$ver*.tar*)
sudo echo "Found archive: $archive"
declare -a arr=("c++" "fortran" "go" "objc" "obj-c++")
lang="c"
echo -e "\n***Add Compilers of your choice, default is n (not select) for every step***\n"
for i in "${arr[@]}"
do
sudo echo
read -e -p "Add $i (y/n)?: " choice
if [ "$choice" == "y" ] || [ "$choice" == "Y" ]; then
lang="$lang,$i"
fi
sudo echo "Selected Languages: $lang"
done
read -e -p "Number of simultaneous tasks?: " -i "5" sim
if [[ $sim =~ ^[\-0-9]+$ ]] && (( sim > 0)); then
  sim=$sim
else
  sim=5
fi
read -e -p "Install dependencies (requires network connection) (y/n)?: " -i "n" dep
if [ "$dep" == "y" ] || [ "$dep" == "Y" ]; then
apt-get install libmpfr-dev libgmp3-dev libmpc-dev libc6-dev flex bison gcc g++
fi
sudo -u $USER tar xvjf $archive
cd gcc-*$ver* || exit 1
gccname=`basename "$PWD"`
cd ..
sudo -u $USER rm -rf $HOME/_JTMP_
sudo -u $USER mkdir $HOME/_JTMP_
sudo -u $USER mv $gccname $HOME/_JTMP_/
cd $HOME/_JTMP_
sudo -u $USER mkdir gcc-build
cd gcc-build
sudo -s <<EOF
sudo -u $USER $HOME/_JTMP_/$gccname/configure        \
    --prefix=/usr                                    \
    --libdir=/usr/lib                                \
    --enable-shared                                  \
    --program-suffix=-$ver                           \
    --enable-linker-build-id                         \
    --libexecdir=/usr/lib                            \
    --without-included-gettext                       \
    --enable-threads=posix                           \
    --libdir=/usr/lib                                \
    --enable-nls --with-sysroot=/                    \
    --enable-clocale=gnu                             \
    --enable-libstdcxx-debug                         \
    --enable-libstdcxx-time=yes                      \
    --enable-gnu-unique-object                       \
    --enable-plugin                                  \
    --enable-java-awt=gtk --enable-gtk-cairo         \
    --with-arch-directory=amd64                      \
    --with-ecj-jar=/usr/share/java/eclipse-ecj.jar   \
    --enable-objc-gc                                 \
    --enable-multiarch                               \
    --disable-werror                                 \
    --with-arch-32=i686                              \
    --with-abi=m64                                   \
    --with-multilib-list=m32,m64,mx32                \
    --with-tune=generic                              \
    --build=x86_64-linux-gnu                         \
    --host=x86_64-linux-gnu                          \
    --target=x86_64-linux-gnu                        \
    --enable-threads=posix                           \
    --enable-__cxa_atexit                            \
    --enable-clocale=gnu                             \
    --disable-multilib                               \
    --with-system-zlib                               \
    --enable-languages=$lang &&
sudo -u $USER make --jobs=$sim
make install
sudo -u $USER rm -rf $HOME/_JTMP_
EOF
